# frozen_string_literal: true

source "https://rubygems.org"

gem 'sorbet-static-and-runtime'
gem 'tapioca', require: false, :group => :development
gem 'sorbet-struct-comparable'
gem 'flamegraph'
gem 'stackprof'
gem 'parallel'
gem 'byebug'

gem "pry", "~> 0.14.2"
