# frozen_string_literal: true

source "https://rubygems.org"

gem 'sorbet-static-and-runtime'
gem 'sorbet-struct-comparable'

gem 'tapioca', require: false, :group => :development
gem 'rubocop', require: false, :group => :development

gem 'flamegraph', require: false, :group => :development
gem 'stackprof', require: false, :group => :development
gem 'parallel'
gem 'byebug', require: false, :group => :development

gem "pry", require: false, :group => :development
