# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sorbet-static-and-runtime", "~> 0.5.11670"
gem "sorbet-struct-comparable", "~> 1.3"

gem 'byebug', require: false, :group => :development
