# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "sorbet", "~> 0.5.10932"

gem "tapioca", "~> 0.11.8", :group => :development

gem "sorbet-runtime", "~> 0.5.10932"

gem "rubocop", "~> 1.74"

gem "ruby-lsp", "~> 0.17.16"
