[package]
name = "aoc19"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
itertools = "0.15.0"
rand = "0.10.2"
rayon = "1.12.0"

[[bin]]
name = "intcode-vm"
path = "src/bin/int_vm.rs"

[[bin]]
name = "day01"
path = "src/bin/day01.rs"

[[bin]]
name = "day02"
path = "src/bin/day02.rs"

[[bin]]
name = "day05"
path = "src/bin/day05.rs"

[[bin]]
name = "day07"
path = "src/bin/day07.rs"

[[bin]]
name = "day09"
path = "src/bin/day09.rs"

[[bin]]
name = "day11"
path = "src/bin/day11.rs"

[[bin]]
name = "day13"
path = "src/bin/day13.rs"

[[bin]]
name = "day15"
path = "src/bin/day15.rs"

[[bin]]
name = "day17"
path = "src/bin/day17.rs"

[[bin]]
name = "day19"
path = "src/bin/day19.rs"

[[bin]]
name = "day21"
path = "src/bin/day21.rs"

[[bin]]
name = "day23"
path = "src/bin/day23.rs"

[[bin]]
name = "day25"
path = "src/bin/day25.rs"
